

const Data = {

English : {
    Home:{
            h1: 'Renting has never been easier',
            h2:'MEET ATAR',
            p1:'Whether you’re a landlord or agent looking to list and manage your properties or a tenant looking to find your dream home, there’s something for everyone here at Atar.',
            h3:'Download our apps today and learn more. ',
            h4:'List Your Home',
            p2:'Listing homes is much more than simply placing ads, and our aim is to find you the right tenant for the right price, all the while making sure your home looks its best.',
            icon1:'Accurate Listings',
            icon2:'3D Virtual Tours & Floorplans',
            icon3:'Visit Management for Your Properties',
            mobile1:'3D Virtual Tours & Floorplans',
            mobile2:'Visit Management For Your Properties',
            button1:'List your home today',
            h5:'Manage Your Home',
            p3:'We’re aware of the hassle that comes with managing homes. No more disputes and unexpected surprises. Simply manage your properties, generate reports, and interact with tenants from the comfort of your phone screen.',
            icon3:'Real-time Status Summaries',
            icon4:'Manage Maintenance & Other Requests',
            icon5:'Track Your Income & Expenses',
            icon6:'Provide Access to Users',
            button2:'Manage your property today',
            mobile3:'Real-time Status Summaries',
            mobile4:'Manage Maintenance & Other Requests',
            mobile5:'Track your Income & Expenses',
            button3:'Manage your property today',
            h6:'Find Your Dream Home',
            p4:'We understand how difficult it can be to find the right home for yourself and your family. Through our listing platform, you can find accurate listings with detailed information and search and filter in the ways that really matter.',
            icon7:'Search & Select',
            icon8:'3D Walkthroughs',
            icon9:'Schedule a Visit',
            button4:'Find your dream home today',  
        },
    About:{
            h1:'Not your typical property management & listing solution',
            p1:'Our vision at Atar is to digitally transform everything it means to live in and manage homes. The future of home-listing and property management is here.',
            h2:'Meet Atar',
            p2:'Aren’t we all tired of the process of finding our dream home? Or looking for reliable tenants to rent our homes? The cost, the hassle, the inaccurate ads, and most importantly the time spent. So, we decided to take matters into our own hands. To make renting easier and the ability to find a suitable home for all and an enjoyable journey you deserve.',
            p3:'Meet Atar. An easy-to-use, user-friendly platform that has the ability to search for homes with different specifications and filters. Atar focuses on quality, validity, and comprehensiveness when it comes to 3D floor plans. You no longer have to deal with outdated pictures and inaccurate information! Our 3D tech is also VR compatible which means, which will allow you to have walk-throughs right at your fingertips. With Atar, you also have the ability to schedule a visit at your connivence – Pick a day and time that suits your needs in finding your dream home with Atar.',
            p4:'We know that a home is not a place, it’s a feeling. So, we took the responsibility of understanding the true wants of renters and the needs of the landlords. We have created a well-comprehensive platform that will efficiently allow you to simply sit back and begin your journey from the comfort of your own home.',
            h3:'Meet AtarCloud',
            p5:'Atar Cloud is a cloud-based property management system that allows you to manage your payment collections, rental agreements, maintenance requests, onboarding tenants, managing lease, communicate with your tenants, generating reports, and so much more.',
        },
    ListYourProperty:{
        h1:'Redefining the home rental process',
        p1:'Finding the right tenants just got easier with Atar. Start by simply filling out the form and and our team will reach out to you soon.',
        h2:'How Atar Works',
        icon1:'Fill out the form',
        icon2:'A team member will reach out',
        icon3:'We’ll prepare your listings',
        icon4:'Your properties will be listing on the Atar website and mobile application',
        h3:'The Benefits of Using Atar',
        h4:'Renting with Atar',
        h5:'Traditional property management companies',
        tick1:'Quick and easy forms',
        tick2:'Professional photography',
        tick3:'3D Virtual Tours and Floorplans',
        tick4:'Visit scheduling',
        cross1:'Tedious forms',
        cross2:'Limited visibility',
        cross3:'Unsuitable tenants',
        cross4:'Inconvenient viewing times',
        h6:'3D Virtual Tours & Floorplans',
        h7:'Ready to list your property with Atar?',
        button1:'Get Started',
        },
    Contact:{
        h1:'Contact',
        p1:'For all enquiries, please email us using the form below.',
        input1:'First Name',
        input2:'Last Name',
        input3:"What's your email ?",
        input4:'Enquiry',
        button1:'Submit',
    }   
  },
  Arabic : {
    Home:{
            h1: 'Renting has never been easier',
            h2:'MEET ATAR',
            p1:'Whether you’re a landlord or agent looking to list and manage your properties or a tenant looking to find your dream home, there’s something for everyone here at Atar.',
            h3:'Download our apps today and learn more. ',
            h4:'List Your Home',
            p2:'Listing homes is much more than simply placing ads, and our aim is to find you the right tenant for the right price, all the while making sure your home looks its best.',
            icon1:'Accurate Listings',
            icon2:'3D Virtual Tours & Floorplans',
            icon3:'Visit Management for Your Properties',
            mobile1:'3D Virtual Tours & Floorplans',
            mobile2:'Visit Management For Your Properties',
            button1:'List your home today',
            h5:'Manage Your Home',
            p3:'We’re aware of the hassle that comes with managing homes. No more disputes and unexpected surprises. Simply manage your properties, generate reports, and interact with tenants from the comfort of your phone screen.',
            icon3:'Real-time Status Summaries',
            icon4:'Manage Maintenance & Other Requests',
            icon5:'Track Your Income & Expenses',
            icon6:'Provide Access to Users',
            button2:'Manage your property today',
            mobile3:'Real-time Status Summaries',
            mobile4:'Manage Maintenance & Other Requests',
            mobile5:'Track your Income & Expenses',
            button3:'Manage your property today',
            h6:'Find Your Dream Home',
            p4:'We understand how difficult it can be to find the right home for yourself and your family. Through our listing platform, you can find accurate listings with detailed information and search and filter in the ways that really matter.',
            icon7:'Search & Select',
            icon8:'',
            icon9:'3D Walkthroughs',
            icon10:'Schedule a Visit',
            button4:'Find your dream home today',  
        },
    About:{
            h1:'Not your typical property management & listing solution',
            p1:'Our vision at Atar is to digitally transform everything it means to live in and manage homes. The future of home-listing and property management is here.',
            h2:'Meet Atar',
            p2:'Aren’t we all tired of the process of finding our dream home? Or looking for reliable tenants to rent our homes? The cost, the hassle, the inaccurate ads, and most importantly the time spent. So, we decided to take matters into our own hands. To make renting easier and the ability to find a suitable home for all and an enjoyable journey you deserve.',
            p3:'Meet Atar. An easy-to-use, user-friendly platform that has the ability to search for homes with different specifications and filters. Atar focuses on quality, validity, and comprehensiveness when it comes to 3D floor plans. You no longer have to deal with outdated pictures and inaccurate information! Our 3D tech is also VR compatible which means, which will allow you to have walk-throughs right at your fingertips. With Atar, you also have the ability to schedule a visit at your connivence – Pick a day and time that suits your needs in finding your dream home with Atar.',
            p4:'We know that a home is not a place, it’s a feeling. So, we took the responsibility of understanding the true wants of renters and the needs of the landlords. We have created a well-comprehensive platform that will efficiently allow you to simply sit back and begin your journey from the comfort of your own home.',
            h3:'Meet AtarCloud',
            p5:'Atar Cloud is a cloud-based property management system that allows you to manage your payment collections, rental agreements, maintenance requests, onboarding tenants, managing lease, communicate with your tenants, generating reports, and so much more.',
        },
    ListYourProperty:{
        h1:'Redefining the home rental process',
        p1:'Finding the right tenants just got easier with Atar. Start by simply filling out the form and and our team will reach out to you soon.',
        h2:'How Atar Works',
        icon1:'Fill out the form',
        icon2:'A team member will reach out',
        icon3:'We’ll prepare your listings',
        icon4:'Your properties will be listing on the Atar website and mobile application',
        h3:'The Benefits of Using Atar',
        h4:'Renting with Atar',
        h5:'Traditional property management companies',
        tick1:'Quick and easy forms',
        tick2:'Professional photography',
        tick3:'3D Virtual Tours and Floorplans',
        tick4:'Visit scheduling',
        cross1:'Tedious forms',
        cross2:'Limited visibility',
        cross3:'Unsuitable tenants',
        cross4:'Inconvenient viewing times',
        h6:'3D Virtual Tours & Floorplans',
        h7:'Ready to list your property with Atar?',
        button1:'Get Started',
        },
    Contact:{
        h1:'Contact',
        p1:'For all enquiries, please email us using the form below.',
        input1:'First Name',
        input2:'Last Name',
        input3:"What's your email ?",
        input4:'Enquiry',
        button1:'Submit',
    }   
  }
}


export default Data;